name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node: [lts/-1, lts/*, latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node }}
        cache: 'npm'
    - uses: seanmiddleditch/gha-setup-ninja@master
    - run: cd configure && npm ci
    - run: npm run configure
    - run: ninja -k 0
    - run: npm run docs

  deploy:
    needs: build
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: latest
        cache: 'npm'
    - uses: seanmiddleditch/gha-setup-ninja@master
    - run: cd configure && npm ci
    - run: npm run configure
    - run: ninja -k 0 prep-for-docs
    - run: npm run docs
    - uses: actions/upload-pages-artifact@v3
      with:
        path: "./docs"
